### ISSUE TITLE
Ошибка отправки SMS ERROR=102: APIKEY NOT FOUND!

### ISSUE THREAD

**Issue by 7dir** [smspilot/smspilot#1]

**Comment by shuchkin** [comment]
проверьте значение ключа, должно совпадать с указанным в настройках
https://smspilot.ru/my-settings.php

**Comment by 7dir** [comment]
```php

if (!defined('SMSPILOT_API')) define('SMSPILOT_API', 'http://smspilot.ru/api.php');
if (!defined('SMSPILOT_APIKEY')) define('SMSPILOT_APIKEY', '659D1L00771996J1IL9E7M737BE0O469Q3V6001TD20O745N30G1OE6166FL3L45');
if (!defined('SMSPILOT_CHARSET')) define('SMSPILOT_CHARSET', 'UTF-8');
if (!defined('SMSPILOT_FROM')) define('SMSPILOT_FROM', ''); // new in 1.8.1

```

**Comment by 7dir** [comment]
Проходит в браузере
http://smspilot.ru/api.php?send=%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0&to=79622841331&apikey=659D1L00771996J1IL9E7M737BE0O469Q3V6001TD20O745N30G1OE6166FL3L45

а чз php

<?php

define('SMSPILOT_APIKEY', '659D1L00771996J1IL9E7M737BE0O469Q3V6001TD20O745N30G1OE6166FL3L45');
include('smspilot.php');
sms('79622841331', 'Статус заказа №');

не хочет

**Comment by shuchkin** [comment]
ты че делаешь )

**Comment by 7dir** [comment]
сменю сейчас ключ )

**Comment by shuchkin** [comment]
пиши в whatsapp +79087964781 или skype serg_shuchkin

**Comment by shuchkin** [comment]
как минимум включи отображение ошибок
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

**Comment by shuchkin** [comment]
в телегу тоже можно постучаться +79087964781

**Comment by 7dir** [comment]
пишу

**Comment by shuchkin** [comment]
сокеты закрыты? - если виртуальный хостинг, то такое бывает

**Comment by 7dir** [comment]
локально проверяю на винде и консоли

щас на хостинге проверю

**Comment by 7dir** [comment]
на хостинге работает!

**Comment by 7dir** [comment]
значит на винде глюк, почему тогда ошибка на ключ кажет?
